
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.1.0'
 * Timestamp: Wed Feb 12 2020 15:35:02 GMT-0500 (Eastern Standard Time)
 *
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class BrightcoveVideo extends ContentItem {
    public videoTitle: Elements.TextElement;
    constructor() {
        super({
            propertyResolver: ((elementName: string) => {
                if (elementName === 'video_title') {
                    return 'videoTitle';
                }
                return elementName;
            })
        });
    }
}
