
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.1.0'
 * Timestamp: Wed Feb 12 2020 15:35:02 GMT-0500 (Eastern Standard Time)
 *
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class SimplePage extends ContentItem {
    public description: Elements.RichTextElement;
    public title: Elements.TextElement;
    public slug: Elements.UrlSlugElement;
    public navigationSubNavigationTitle: Elements.TextElement;
    public navigationNavigation: Elements.TaxonomyElement;
    constructor() {
        super({
            propertyResolver: ((elementName: string) => {
                if (elementName === 'navigation__sub_navigation_title') {
                    return 'navigationSubNavigationTitle';
                }
                if (elementName === 'navigation__navigation') {
                    return 'navigationNavigation';
                }
                return elementName;
            })
        });
    }
}
