import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.1.0'
 * Timestamp: Wed Feb 12 2020 09:57:05 GMT-0500 (Eastern Standard Time)
 */
export class HomePage extends ContentItem {
  constructor() {
    super({
      richTextResolver: (rawElement) => {
        debugger;
      },
      itemResolver: (rawElement) => {
        debugger;
      },
      linkedItemResolver: (rawElement) => {
        debugger;
      },
      urlSlugResolver: (rawElement) => {
        debugger;
      },
      propertyResolver: elementName => {
        debugger;
        if (elementName === 'about_title') {
          return 'aboutTitle';
        }
        if (elementName === 'about_description') {
          return 'aboutDescription';
        }
        if (elementName === 'about_image') {
          return 'aboutImage';
        }
        if (elementName === 'hero_image') {
          return 'heroImage';
        }
        if (elementName === 'page_title') {
          return 'pageTitle';
        }
        return elementName;
      }
    });
  }
}

export class Promo extends ContentItem {
  constructor() {
    super({
      richTextResolver: (rawElement) => {
        debugger;
      },
      itemResolver: (rawElement) => {
        debugger;
      },
      linkedItemResolver: (rawElement) => {
        debugger;
      },
      urlSlugResolver: (rawElement) => {
        debugger;
      },
      propertyResolver: elementName => {
        if (elementName === 'background_image') {
          return 'backgroundImage';
        }
        if (elementName === 'learn_more') {
          return 'learnMore';
        }
        return elementName;
      }
    });
  }
}
