
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.1.0'
 * Timestamp: Wed Feb 12 2020 09:57:05 GMT-0500 (Eastern Standard Time)
 */
export class SimplePage extends ContentItem {
        constructor() {
        super({
            propertyResolver: ((elementName) => {
                if (elementName === 'navigation__sub_navigation_title') {
                    return 'navigationSubNavigationTitle';
                }
                if (elementName === 'navigation__navigation') {
                    return 'navigationNavigation';
                }
                return elementName;
            })
        });
    }
}
